fix: subscribe to lambda and firehose
observeinc/terraform-aws-collection pull request #53
Opened 2023-03-11 04:32 UTC by luke-zhu

## What does this PR do?

This forwards log data from our Lambda function and Firehose delivery stream to the
customer's Observe cluster.

## Testing

Tested in eng. Data was forwarded to our O2 cluster.

2023-03-11 19:52 UTC, bendrucker requested changes

2023-03-11 19:52 UTC, bendrucker commented on subscription.tf
> +  observe_log_groups  = [aws_cloudwatch_log_group.group.name, "/aws/lambda/${var.name}"]
Implicit dependency on Lambda here, likely to fail on initial creation. Reverse engineering of IDs is always a red flag for this reason. 

The general approach to this is to declare the CW logs group with Terraform, reverse engineering the name there and only there. AWS will use that existing log group, at least in my experience with other services with a similar problem like EKS. 

But this is a breaking change, as it requires either replacement of the Lambda (new name) or using `terraform import` for the log group. 

Doable if you consider this from the start but a chore if you're trying to migrate.

2023-03-11 19:52 UTC, bendrucker commented on subscription.tf
> +resource "aws_iam_role_policy_attachment" "observe_subscription_filter" {
Avoid role policy attachments unless you explicitly intend for the caller to be able to attach more policies. Prefer authoritative whenever possible, in this case setting `managed_policy_arns` on the role.

2023-03-13 17:26 UTC, jta reviewed
We have a submodule in https://github.com/observeinc/terraform-aws-lambda/tree/main/modules/cloudwatch_logs_subscription that does most of this for you. We should use that when the time comes, but we have to hold off for now otherwise users will run into a race condition:
- prior to 2.x, users subscribed log group `/aws/lambda/${var.name}` via the "automatic" cw logs subscription
- we removed this subscription in 2.0 because we wanted to make the "automatic" component opt-in
- if we were to introduce the proposed change, users upgrading from versions prior to 2.x will attempt to subscribe `/aws/lambda/${var.name}` explicitly at the same time the prior subscription is being removed. Given the cloudformation stack is slower to take hold, a race condition will ensure.

2023-03-16 18:45 UTC, closed without merging